from io import BytesIO
import os
import threading

from fastapi import FastAPI, File, Form, UploadFile
from PIL import Image

import torch
from transformers import (
    AutoProcessor,
    Qwen2_5_VLForConditionalGeneration,
)


app = FastAPI(
    title="Pokemon Text Model Service",
    version="1.0.0",
)


# ----------------------------------------
# Device / Model
# ----------------------------------------

device = "cuda" if torch.cuda.is_available() else "cpu"

text_processor = None
text_model = None

inference_lock = threading.Lock()


# ----------------------------------------
# Setup
# ----------------------------------------

def setup():
    global text_processor
    global text_model

    token = os.getenv("HF_TOKEN")

    model_name = os.getenv(
        "TEXT_MODEL",
        "Qwen/Qwen2.5-VL-7B-Instruct",
    )

    print(f"Loading text model: {model_name}")
    print(f"Using device: {device}")

    text_processor = AutoProcessor.from_pretrained(
        model_name,
        token=token,
    )

    if device == "cuda":
        dtype = torch.bfloat16
    else:
        dtype = torch.float32

    text_model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        model_name,
        token=token,
        dtype=dtype,
        device_map="auto" if device == "cuda" else None,
        attn_implementation="sdpa",
    )

    if device == "cpu":
        text_model.to("cpu")

    text_model.eval()

    print(
        f"Text model ready on {device}: {model_name}"
    )


@app.on_event("startup")
def startup():
    setup()


# ----------------------------------------
# Health
# ----------------------------------------

@app.get("/health")
def health():
    return {
        "status": "ok",
        "model_loaded": text_model is not None,
        "device": device,
    }


# ----------------------------------------
# Generic Image -> Text
# ----------------------------------------

def generate_text(
    image: Image.Image,
    prompt: str,
    max_new_tokens: int = 100,
) -> str:

    image = image.convert("RGB")

    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": image,
                },
                {
                    "type": "text",
                    "text": prompt,
                },
            ],
        }
    ]

    inputs = text_processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    )

    # Move tensors to the same device as the model.
    if device == "cuda":
        inputs = inputs.to(text_model.device)
    else:
        inputs = inputs.to("cpu")

    with torch.inference_mode():

        generated_ids = text_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
        )

    # Remove the input tokens so we only return
    # the newly generated response.
    input_length = inputs["input_ids"].shape[-1]

    generated_ids = generated_ids[
        :, input_length:
    ]

    generated_text = text_processor.batch_decode(
        generated_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=True,
    )[0].strip()

    return generated_text


# ----------------------------------------
# Generate Name + Description
# ----------------------------------------

@app.post("/generate")
def generate(
    image: UploadFile = File(...),
):

    input_image = Image.open(
        BytesIO(image.file.read())
    ).convert("RGB")

    # ----------------------------------------
    # Generate creature name
    # ----------------------------------------

    name_prompt = """
Look at the creature in the image.

Create a unique fantasy creature name for it.

Requirements:
- One single name.
- 1 or 2 words maximum.
- Easy to pronounce.
- Suitable for a creature in a monster-collecting RPG.
- Do not use an existing Pokémon name.
- Do not explain the name.
- Return only the creature name.
"""

    # ----------------------------------------
    # Generate description
    # ----------------------------------------

    description_prompt = """
Look at the creature in the image.

Write a short creature description for a monster-collecting RPG.

Requirements:
- 1 to 2 sentences.
- Describe its appearance, nature, or behavior.
- Make it sound like an official creature encyclopedia entry.
- Do not mention Pokémon.
- Do not mention that the creature was generated by AI.
- Do not explain your reasoning.
- Return only the description.
"""

    # ----------------------------------------
    # Generate both
    # ----------------------------------------

    with inference_lock:

        name = generate_text(
            image=input_image,
            prompt=name_prompt,
            max_new_tokens=20,
        )

        description = generate_text(
            image=input_image,
            prompt=description_prompt,
            max_new_tokens=100,
        )

    return {
        "name": name,
        "description": description,
    }