from io import BytesIO
import json
import logging
import os
import threading
from time import perf_counter

from fastapi import FastAPI, File, HTTPException, UploadFile
from PIL import Image

import torch
from transformers import (
    AutoProcessor,
    Qwen2_5_VLForConditionalGeneration,
)


app = FastAPI(
    title="Pokemon Text Model Service",
    version="1.0.0",
)
logger = logging.getLogger("uvicorn.error")


# ----------------------------------------
# Device / Model
# ----------------------------------------

device = "cuda" if torch.cuda.is_available() else "cpu"

text_processor = None
text_model = None

inference_lock = threading.Lock()


# ----------------------------------------
# Setup
# ----------------------------------------

def setup():
    global text_processor
    global text_model

    token = os.getenv("HF_TOKEN")

    model_name = os.getenv(
        "TEXT_MODEL",
        "Qwen/Qwen2.5-VL-3B-Instruct",
    )

    print(f"Loading text model: {model_name}")
    print(f"Using device: {device}")

    text_processor = AutoProcessor.from_pretrained(
        model_name,
        token=token,
    )

    if device == "cuda":
        dtype = torch.bfloat16
    else:
        dtype = torch.float32

    text_model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        model_name,
        token=token,
        dtype=dtype,
        device_map="auto" if device == "cuda" else None,
        attn_implementation="sdpa",
    )

    if device == "cpu":
        text_model.to("cpu")

    text_model.eval()

    loaded_devices = sorted(
        {
            str(loaded_device)
            for loaded_device in getattr(text_model, "hf_device_map", {}).values()
        }
    )
    if not loaded_devices:
        loaded_devices = [device]
    print(f"Text model ready on {', '.join(loaded_devices)}: {model_name}")
    if "cpu" in loaded_devices or "disk" in loaded_devices:
        print("Text model offload is enabled; CPU or disk offload can slow generation.")


@app.on_event("startup")
def startup():
    setup()


# ----------------------------------------
# Health
# ----------------------------------------

@app.get("/health")
def health():
    return {
        "status": "ok",
        "model_loaded": text_model is not None,
        "device": device,
    }


# ----------------------------------------
# Generic Image -> Text
# ----------------------------------------

def generate_text(
    image: Image.Image,
    prompt: str,
    max_new_tokens: int = 100,
) -> str:

    image = image.convert("RGB")

    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": image,
                },
                {
                    "type": "text",
                    "text": prompt,
                },
            ],
        }
    ]

    inputs = text_processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    )

    # Move tensors to the same device as the model.
    if device == "cuda":
        inputs = inputs.to(text_model.device)
    else:
        inputs = inputs.to("cpu")

    generation_started = perf_counter()
    with torch.inference_mode():

        generated_ids = text_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
        )
    logger.info(
        "text timing stage=model_generate elapsed_seconds=%.2f output_tokens=%d",
        perf_counter() - generation_started,
        generated_ids.shape[-1] - inputs["input_ids"].shape[-1],
    )

    # Remove the input tokens so we only return
    # the newly generated response.
    input_length = inputs["input_ids"].shape[-1]

    generated_ids = generated_ids[
        :, input_length:
    ]

    generated_text = text_processor.batch_decode(
        generated_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    )[0].strip()

    return generated_text


# ----------------------------------------
# Generate Name + Description
# ----------------------------------------

@app.post("/generate")
def generate(
    image: UploadFile = File(...),
):

    input_image = Image.open(
        BytesIO(image.file.read())
    ).convert("RGB")

    # ----------------------------------------
    # Generate both
    # ----------------------------------------

    combined_prompt = """
Look at the creature in the image and return one JSON object with exactly these
two string fields: "name" and "description".

Requirements for name:
- Create a unique fantasy creature name.
- Use 1 word maximum; make it easy to pronounce.
- Do not reuse an existing Pokemon name.

Requirements for description:
- Write 1 to 2 sentences describing its appearance, nature, or behavior.
- Make it sound like an official creature encyclopedia entry.
- Do not mention Pokemon or that the creature was generated by AI.

Do not include markdown, commentary, or any keys other than "name" and
"description". Return valid JSON only.
"""

    with inference_lock:
        generated_text = generate_text(
            image=input_image,
            prompt=combined_prompt,
            max_new_tokens=140,
        )

    try:
        json_start = generated_text.index("{")
        generated_data, _ = json.JSONDecoder().raw_decode(
            generated_text[json_start:]
        )
        name = generated_data["name"].strip()
        description = generated_data["description"].strip()
    except (ValueError, KeyError, AttributeError, TypeError) as error:
        raise HTTPException(
            status_code=502,
            detail="Text model returned an invalid name/description response",
        ) from error

    if not name or not description:
        raise HTTPException(
            status_code=502,
            detail="Text model returned an empty name or description",
        )

    return {
        "name": name,
        "description": description,
    }
