# Generated by Django 5.2.10 on 2026-08-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0033_itemprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
    ]
